//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedU.StudentLookup {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://iis2.it.ilstu.edu/", ConfigurationName="StudentLookup.StudentLookupSoap")]
    public interface StudentLookupSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://iis2.it.ilstu.edu/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://iis2.it.ilstu.edu/HelloWorld", ReplyAction="*")]
        LinkedU.StudentLookup.HelloWorldResponse HelloWorld(LinkedU.StudentLookup.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iis2.it.ilstu.edu/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<LinkedU.StudentLookup.HelloWorldResponse> HelloWorldAsync(LinkedU.StudentLookup.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://iis2.it.ilstu.edu/", Order=0)]
        public LinkedU.StudentLookup.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LinkedU.StudentLookup.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://iis2.it.ilstu.edu/", Order=0)]
        public LinkedU.StudentLookup.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(LinkedU.StudentLookup.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://iis2.it.ilstu.edu/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentLookupSoapChannel : LinkedU.StudentLookup.StudentLookupSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentLookupSoapClient : System.ServiceModel.ClientBase<LinkedU.StudentLookup.StudentLookupSoap>, LinkedU.StudentLookup.StudentLookupSoap {
        
        public StudentLookupSoapClient() {
        }
        
        public StudentLookupSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentLookupSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentLookupSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentLookupSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LinkedU.StudentLookup.HelloWorldResponse LinkedU.StudentLookup.StudentLookupSoap.HelloWorld(LinkedU.StudentLookup.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            LinkedU.StudentLookup.HelloWorldRequest inValue = new LinkedU.StudentLookup.HelloWorldRequest();
            inValue.Body = new LinkedU.StudentLookup.HelloWorldRequestBody();
            LinkedU.StudentLookup.HelloWorldResponse retVal = ((LinkedU.StudentLookup.StudentLookupSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LinkedU.StudentLookup.HelloWorldResponse> LinkedU.StudentLookup.StudentLookupSoap.HelloWorldAsync(LinkedU.StudentLookup.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkedU.StudentLookup.HelloWorldResponse> HelloWorldAsync() {
            LinkedU.StudentLookup.HelloWorldRequest inValue = new LinkedU.StudentLookup.HelloWorldRequest();
            inValue.Body = new LinkedU.StudentLookup.HelloWorldRequestBody();
            return ((LinkedU.StudentLookup.StudentLookupSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
