//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
<<<<<<< HEAD
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedU
{


    public partial class Logoff
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
=======
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedU {
    
    
    public partial class Logoff {
>>>>>>> dd80ba928738314105fd8e21c52f3d1a07b72159
    }
}
