//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedU.SMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://it.ilstu.edu/", ConfigurationName="SMS.TextSender")]
    public interface TextSender {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://it.ilstu.edu/TextSender/sendSMSRequest", ReplyAction="http://it.ilstu.edu/TextSender/sendSMSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LinkedU.SMS.sendSMSResponse sendSMS(LinkedU.SMS.sendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.ilstu.edu/TextSender/sendSMSRequest", ReplyAction="http://it.ilstu.edu/TextSender/sendSMSResponse")]
        System.Threading.Tasks.Task<LinkedU.SMS.sendSMSResponse> sendSMSAsync(LinkedU.SMS.sendSMSRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://it.ilstu.edu/TextSender/getCarriersRequest", ReplyAction="http://it.ilstu.edu/TextSender/getCarriersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LinkedU.SMS.getCarriersResponse getCarriers(LinkedU.SMS.getCarriersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.ilstu.edu/TextSender/getCarriersRequest", ReplyAction="http://it.ilstu.edu/TextSender/getCarriersResponse")]
        System.Threading.Tasks.Task<LinkedU.SMS.getCarriersResponse> getCarriersAsync(LinkedU.SMS.getCarriersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMS", WrapperNamespace="http://it.ilstu.edu/", IsWrapped=true)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://it.ilstu.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string carrier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://it.ilstu.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telephoneNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://it.ilstu.edu/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(string carrier, string telephoneNum, string text) {
            this.carrier = carrier;
            this.telephoneNum = telephoneNum;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSResponse", WrapperNamespace="http://it.ilstu.edu/", IsWrapped=true)]
    public partial class sendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://it.ilstu.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCarriers", WrapperNamespace="http://it.ilstu.edu/", IsWrapped=true)]
    public partial class getCarriersRequest {
        
        public getCarriersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCarriersResponse", WrapperNamespace="http://it.ilstu.edu/", IsWrapped=true)]
    public partial class getCarriersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://it.ilstu.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getCarriersResponse() {
        }
        
        public getCarriersResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TextSenderChannel : LinkedU.SMS.TextSender, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextSenderClient : System.ServiceModel.ClientBase<LinkedU.SMS.TextSender>, LinkedU.SMS.TextSender {
        
        public TextSenderClient() {
        }
        
        public TextSenderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextSenderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextSenderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextSenderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LinkedU.SMS.sendSMSResponse LinkedU.SMS.TextSender.sendSMS(LinkedU.SMS.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public int sendSMS(string carrier, string telephoneNum, string text) {
            LinkedU.SMS.sendSMSRequest inValue = new LinkedU.SMS.sendSMSRequest();
            inValue.carrier = carrier;
            inValue.telephoneNum = telephoneNum;
            inValue.text = text;
            LinkedU.SMS.sendSMSResponse retVal = ((LinkedU.SMS.TextSender)(this)).sendSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LinkedU.SMS.sendSMSResponse> LinkedU.SMS.TextSender.sendSMSAsync(LinkedU.SMS.sendSMSRequest request) {
            return base.Channel.sendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkedU.SMS.sendSMSResponse> sendSMSAsync(string carrier, string telephoneNum, string text) {
            LinkedU.SMS.sendSMSRequest inValue = new LinkedU.SMS.sendSMSRequest();
            inValue.carrier = carrier;
            inValue.telephoneNum = telephoneNum;
            inValue.text = text;
            return ((LinkedU.SMS.TextSender)(this)).sendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LinkedU.SMS.getCarriersResponse LinkedU.SMS.TextSender.getCarriers(LinkedU.SMS.getCarriersRequest request) {
            return base.Channel.getCarriers(request);
        }
        
        public string[] getCarriers() {
            LinkedU.SMS.getCarriersRequest inValue = new LinkedU.SMS.getCarriersRequest();
            LinkedU.SMS.getCarriersResponse retVal = ((LinkedU.SMS.TextSender)(this)).getCarriers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LinkedU.SMS.getCarriersResponse> LinkedU.SMS.TextSender.getCarriersAsync(LinkedU.SMS.getCarriersRequest request) {
            return base.Channel.getCarriersAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkedU.SMS.getCarriersResponse> getCarriersAsync() {
            LinkedU.SMS.getCarriersRequest inValue = new LinkedU.SMS.getCarriersRequest();
            return ((LinkedU.SMS.TextSender)(this)).getCarriersAsync(inValue);
        }
    }
}
