//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedU.DistanceFinder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Path", Namespace="http://iis2.it.ilstu.edu/")]
    [System.SerializableAttribute()]
    public partial class Path : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LinkedU.DistanceFinder.TextValue DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LinkedU.DistanceFinder.TextValue DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public LinkedU.DistanceFinder.TextValue Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((object.ReferenceEquals(this.DistanceField, value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public LinkedU.DistanceFinder.TextValue Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((object.ReferenceEquals(this.DurationField, value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceAddress {
            get {
                return this.SourceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceAddressField, value) != true)) {
                    this.SourceAddressField = value;
                    this.RaisePropertyChanged("SourceAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DestinationAddress {
            get {
                return this.DestinationAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationAddressField, value) != true)) {
                    this.DestinationAddressField = value;
                    this.RaisePropertyChanged("DestinationAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextValue", Namespace="http://iis2.it.ilstu.edu/")]
    [System.SerializableAttribute()]
    public partial class TextValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geolocation", Namespace="http://iis2.it.ilstu.edu/")]
    [System.SerializableAttribute()]
    public partial class Geolocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float LatitudeField;
        
        private float LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormattedAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FormattedAddress {
            get {
                return this.FormattedAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FormattedAddressField, value) != true)) {
                    this.FormattedAddressField = value;
                    this.RaisePropertyChanged("FormattedAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://iis2.it.ilstu.edu/", ConfigurationName="DistanceFinder.DistanceFinderSoap")]
    public interface DistanceFinderSoap {
        
        // CODEGEN: Generating message contract since element name GetDistanceResult from namespace http://iis2.it.ilstu.edu/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://iis2.it.ilstu.edu/GetDistance", ReplyAction="*")]
        LinkedU.DistanceFinder.GetDistanceResponse GetDistance(LinkedU.DistanceFinder.GetDistanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iis2.it.ilstu.edu/GetDistance", ReplyAction="*")]
        System.Threading.Tasks.Task<LinkedU.DistanceFinder.GetDistanceResponse> GetDistanceAsync(LinkedU.DistanceFinder.GetDistanceRequest request);
        
        // CODEGEN: Generating message contract since element name street from namespace http://iis2.it.ilstu.edu/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://iis2.it.ilstu.edu/GetLocation", ReplyAction="*")]
        LinkedU.DistanceFinder.GetLocationResponse GetLocation(LinkedU.DistanceFinder.GetLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iis2.it.ilstu.edu/GetLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<LinkedU.DistanceFinder.GetLocationResponse> GetLocationAsync(LinkedU.DistanceFinder.GetLocationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistance", Namespace="http://iis2.it.ilstu.edu/", Order=0)]
        public LinkedU.DistanceFinder.GetDistanceRequestBody Body;
        
        public GetDistanceRequest() {
        }
        
        public GetDistanceRequest(LinkedU.DistanceFinder.GetDistanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://iis2.it.ilstu.edu/")]
    public partial class GetDistanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float sourceLat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float sourceLong;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float destLat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float destLong;
        
        public GetDistanceRequestBody() {
        }
        
        public GetDistanceRequestBody(float sourceLat, float sourceLong, float destLat, float destLong) {
            this.sourceLat = sourceLat;
            this.sourceLong = sourceLong;
            this.destLat = destLat;
            this.destLong = destLong;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistanceResponse", Namespace="http://iis2.it.ilstu.edu/", Order=0)]
        public LinkedU.DistanceFinder.GetDistanceResponseBody Body;
        
        public GetDistanceResponse() {
        }
        
        public GetDistanceResponse(LinkedU.DistanceFinder.GetDistanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://iis2.it.ilstu.edu/")]
    public partial class GetDistanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LinkedU.DistanceFinder.Path GetDistanceResult;
        
        public GetDistanceResponseBody() {
        }
        
        public GetDistanceResponseBody(LinkedU.DistanceFinder.Path GetDistanceResult) {
            this.GetDistanceResult = GetDistanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLocation", Namespace="http://iis2.it.ilstu.edu/", Order=0)]
        public LinkedU.DistanceFinder.GetLocationRequestBody Body;
        
        public GetLocationRequest() {
        }
        
        public GetLocationRequest(LinkedU.DistanceFinder.GetLocationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://iis2.it.ilstu.edu/")]
    public partial class GetLocationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string street;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string zip;
        
        public GetLocationRequestBody() {
        }
        
        public GetLocationRequestBody(string street, string city, string state, string zip) {
            this.street = street;
            this.city = city;
            this.state = state;
            this.zip = zip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLocationResponse", Namespace="http://iis2.it.ilstu.edu/", Order=0)]
        public LinkedU.DistanceFinder.GetLocationResponseBody Body;
        
        public GetLocationResponse() {
        }
        
        public GetLocationResponse(LinkedU.DistanceFinder.GetLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://iis2.it.ilstu.edu/")]
    public partial class GetLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LinkedU.DistanceFinder.Geolocation GetLocationResult;
        
        public GetLocationResponseBody() {
        }
        
        public GetLocationResponseBody(LinkedU.DistanceFinder.Geolocation GetLocationResult) {
            this.GetLocationResult = GetLocationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DistanceFinderSoapChannel : LinkedU.DistanceFinder.DistanceFinderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistanceFinderSoapClient : System.ServiceModel.ClientBase<LinkedU.DistanceFinder.DistanceFinderSoap>, LinkedU.DistanceFinder.DistanceFinderSoap {
        
        public DistanceFinderSoapClient() {
        }
        
        public DistanceFinderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistanceFinderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistanceFinderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistanceFinderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LinkedU.DistanceFinder.GetDistanceResponse LinkedU.DistanceFinder.DistanceFinderSoap.GetDistance(LinkedU.DistanceFinder.GetDistanceRequest request) {
            return base.Channel.GetDistance(request);
        }
        
        public LinkedU.DistanceFinder.Path GetDistance(float sourceLat, float sourceLong, float destLat, float destLong) {
            LinkedU.DistanceFinder.GetDistanceRequest inValue = new LinkedU.DistanceFinder.GetDistanceRequest();
            inValue.Body = new LinkedU.DistanceFinder.GetDistanceRequestBody();
            inValue.Body.sourceLat = sourceLat;
            inValue.Body.sourceLong = sourceLong;
            inValue.Body.destLat = destLat;
            inValue.Body.destLong = destLong;
            LinkedU.DistanceFinder.GetDistanceResponse retVal = ((LinkedU.DistanceFinder.DistanceFinderSoap)(this)).GetDistance(inValue);
            return retVal.Body.GetDistanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LinkedU.DistanceFinder.GetDistanceResponse> LinkedU.DistanceFinder.DistanceFinderSoap.GetDistanceAsync(LinkedU.DistanceFinder.GetDistanceRequest request) {
            return base.Channel.GetDistanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkedU.DistanceFinder.GetDistanceResponse> GetDistanceAsync(float sourceLat, float sourceLong, float destLat, float destLong) {
            LinkedU.DistanceFinder.GetDistanceRequest inValue = new LinkedU.DistanceFinder.GetDistanceRequest();
            inValue.Body = new LinkedU.DistanceFinder.GetDistanceRequestBody();
            inValue.Body.sourceLat = sourceLat;
            inValue.Body.sourceLong = sourceLong;
            inValue.Body.destLat = destLat;
            inValue.Body.destLong = destLong;
            return ((LinkedU.DistanceFinder.DistanceFinderSoap)(this)).GetDistanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LinkedU.DistanceFinder.GetLocationResponse LinkedU.DistanceFinder.DistanceFinderSoap.GetLocation(LinkedU.DistanceFinder.GetLocationRequest request) {
            return base.Channel.GetLocation(request);
        }
        
        public LinkedU.DistanceFinder.Geolocation GetLocation(string street, string city, string state, string zip) {
            LinkedU.DistanceFinder.GetLocationRequest inValue = new LinkedU.DistanceFinder.GetLocationRequest();
            inValue.Body = new LinkedU.DistanceFinder.GetLocationRequestBody();
            inValue.Body.street = street;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip = zip;
            LinkedU.DistanceFinder.GetLocationResponse retVal = ((LinkedU.DistanceFinder.DistanceFinderSoap)(this)).GetLocation(inValue);
            return retVal.Body.GetLocationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LinkedU.DistanceFinder.GetLocationResponse> LinkedU.DistanceFinder.DistanceFinderSoap.GetLocationAsync(LinkedU.DistanceFinder.GetLocationRequest request) {
            return base.Channel.GetLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkedU.DistanceFinder.GetLocationResponse> GetLocationAsync(string street, string city, string state, string zip) {
            LinkedU.DistanceFinder.GetLocationRequest inValue = new LinkedU.DistanceFinder.GetLocationRequest();
            inValue.Body = new LinkedU.DistanceFinder.GetLocationRequestBody();
            inValue.Body.street = street;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip = zip;
            return ((LinkedU.DistanceFinder.DistanceFinderSoap)(this)).GetLocationAsync(inValue);
        }
    }
}
